Update testsuite
 rewrite tests/actions/check-env (92%)
 create mode 100755 tests/check-ld-preload.sh
 create mode 100644 tests/functions

diff --git a/tests/actions/check-env b/tests/actions/check-env
--- a/tests/actions/check-env
+++ b/tests/actions/check-env
@@ -1,12 +1,11 @@
 #!/bin/sh
-prog=$(basename $0)
-die() { echo "$prog: $@" >&2; exit 1; }
-[ -n "$IO_WATCHDOG_TIMEOUT" ] ||  die "IO_WATCHDOG_TIMEOUT not set in action"
-[ -n "$IO_WATCHDOG_PID" ] ||      die "IO_WATCHDOG_TIMEOUT not set in action"
-[ -n "$IO_WATCHDOG_TARGET" ] ||   die "IO_WATCHDOG_TIMEOUT not set in action"
+. ${SRCDIR}/functions
+[ -n "$IO_WATCHDOG_TIMEOUT" ] ||  die "Failed. IO_WATCHDOG_TIMEOUT not set."
+[ -n "$IO_WATCHDOG_PID" ] ||      die "Failed. IO_WATCHDOG_PID not set."
+[ -n "$IO_WATCHDOG_TARGET" ] ||   die "Failed. IO_WATCHDOG_TARGET not set."
 
-echo "$prog: PID $IO_WATCHDOG_PID ($IO_WATCHDOG_TARGET) exited after ${IO_WATCHDOG_TIMEOUT}s."
-echo "$prog: Success"
+log_msg "PID $IO_WATCHDOG_PID ($IO_WATCHDOG_TARGET) exited after ${IO_WATCHDOG_TIMEOUT}s."
+log_msg "Success."
 
 kill $IO_WATCHDOG_PID
 
